### ISSUE TITLE
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

### ISSUE THREAD

**Issue by RENXI-NUS** [spcdot/CopyscAT#27]
Hi, great tool! I got the following error at the step of clusterCNV(). How to resolve it please? Thanks.

```
> #cleanup step
> candidate_cnvs_clean<-clusterCNV(initialResultList = candidate_cnvs,medianIQR = candidate_cnvs[[3]],minDiff=1.5) #= 1.5)
Error in xtfrm.data.frame(x) : cannot xtfrm data frames
```

`> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.6 (Ootpa)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.15.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Singapore
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.68.0                   Biostrings_2.68.1                
 [4] XVector_0.40.0                    CopyscAT_0.40                     MASS_7.3-60                      
 [7] jsonlite_1.8.7                    ggplot2_3.4.3                     sp_2.0-0                         
[10] rtracklayer_1.60.1                GenomicRanges_1.52.0              GenomeInfoDb_1.36.3              
[13] IRanges_2.34.1                    S4Vectors_0.38.2                  gplots_3.1.3                     
[16] tibble_3.2.1                      tidyr_1.3.0                       edgeR_3.42.4                     
[19] limma_3.56.2                      stringr_1.5.0                     mclust_6.0.0                     
[22] changepoint_2.2.4                 zoo_1.8-12                        data.table_1.14.8                
[25] igraph_1.5.1                      FNN_1.1.3.2                       Rtsne_0.16                       
[28] biomaRt_2.56.1                    fastcluster_1.2.3                 NMF_0.26                         
[31] Biobase_2.60.0                    BiocGenerics_0.46.0               cluster_2.1.4                    
[34] rngtools_1.5.2                    registry_0.5-1                    viridis_0.6.4                    
[37] viridisLite_0.4.2                 dplyr_1.1.3                      

loaded via a namespace (and not attached):
 [1] DBI_1.1.3                   bitops_1.0-7                gridExtra_2.3               rlang_1.1.1                
 [5] magrittr_2.0.3              gridBase_0.4-7              matrixStats_1.0.0           compiler_4.3.1             
 [9] RSQLite_2.3.1               png_0.1-8                   vctrs_0.6.3                 reshape2_1.4.4             
[13] pkgconfig_2.0.3             crayon_1.5.2                fastmap_1.1.1               dbplyr_2.3.4               
[17] labeling_0.4.3              caTools_1.18.2              utf8_1.2.3                  Rsamtools_2.16.0           
[21] purrr_1.0.2                 bit_4.0.5                   zlibbioc_1.46.0             cachem_1.0.8               
[25] progress_1.2.2              blob_1.2.4                  DelayedArray_0.26.7         BiocParallel_1.34.2        
[29] parallel_4.3.1              prettyunits_1.2.0           R6_2.5.1                    stringi_1.7.12             
[33] RColorBrewer_1.1-3          SummarizedExperiment_1.30.2 Rcpp_1.0.11                 iterators_1.0.14           
[37] Matrix_1.6-1.1              tidyselect_1.2.0            abind_1.4-5                 yaml_2.3.7                 
[41] rstudioapi_0.15.0           doParallel_1.0.17           codetools_0.2-19            curl_5.0.2                 
[45] lattice_0.21-8              plyr_1.8.8                  withr_2.5.1                 KEGGREST_1.40.0            
[49] BiocFileCache_2.8.0         xml2_1.3.5                  pillar_1.9.0                BiocManager_1.30.22        
[53] filelock_1.0.2              MatrixGenerics_1.12.3       KernSmooth_2.23-21          foreach_1.5.2              
[57] generics_0.1.3              RCurl_1.98-1.12             hms_1.1.3                   munsell_0.5.0              
[61] scales_1.2.1                gtools_3.9.4                glue_1.6.2                  tools_4.3.1                
[65] BiocIO_1.10.0               GenomicAlignments_1.36.0    locfit_1.5-9.8              XML_3.99-0.14              
[69] grid_4.3.1                  AnnotationDbi_1.62.2        colorspace_2.1-0            GenomeInfoDbData_1.2.10    
[73] restfulr_0.0.15             cli_3.6.1                   rappdirs_0.3.3              fansi_1.0.4                
[77] S4Arrays_1.0.6              gtable_0.3.4                digest_0.6.33               farver_2.1.1               
[81] rjson_0.2.21                memoise_2.0.1               lifecycle_1.0.3             httr_1.4.7                 
[85] bit64_4.0.5           `

**Comment by Urja25** [comment]
Same issue! Did you figure out how to resolve this?

**Comment by spcdot** [comment]
Hmm... interesting. I haven't seen this issue come up in my own testing. Can you post an example of what the candidate_cnvs object looks like? I'll take another look at the source and see if I can figure out where that might be coming from.

**Comment by Urja25** [comment]
Could it be because I am using R/4.3.0? I tried installing copyscat on R/4.0 but this was not possible because of installation issues with devtools on this version.
Here is an example of the candidate_cnvs object:

![cnvs](https://github.com/spcdot/CopyscAT/assets/135853774/76c92f0d-7f28-4bbd-b89a-3d8424e654df)

**Comment by spcdot** [comment]
Thanks for posting - the input object looks correct, so I wonder if there's some change to the behaviour of the "order" function in this version of R. I'll look into it and see if I can make some sort of patch for this.

I have most recently installed Copy-scAT successfully in combination with R 4.2.2 -- would using R 4.2 get around your devtools issue?

**Comment by spcdot** [comment]
I tweaked the code of that function slightly, so hopefully it shouldn't throw that error. For me it was coming up as a warning rather than error and the output looked correct, but hopefully it should be resolved or at least less of an issue. Try installing the latest build and let me know if it helps.

**Comment by Urja25** [comment]
Thank you @spcdot!! I re-installed the new build, however, the issue does not get resolved and I still get the same error:
> candidate_cnvs_clean<-clusterCNV(initialResultList = candidate_cnvs,medianIQR = candidate_cnvs[[3]],minDiff=1.5) #= 1.5)
Error in xtfrm.data.frame(x) : cannot xtfrm data frames

Here is my R session info:
![sessioninfo](https://github.com/spcdot/CopyscAT/assets/135853774/83165cd3-4018-4112-a3c4-21f55b33391a)

I also checked to confirm if the updated code was present in the function:
![newfunction](https://github.com/spcdot/CopyscAT/assets/135853774/f0e2e3c2-d9da-4aaf-b1c0-350e4d7985a8)

Unfortunately the cluster I use only has R/4.2 and 4.2.2, and I did try installing the packages there but ran into several errors.

Any other ideas on how to solve this?
